version: "{build}"
clone_depth: 1
build_script:
  - cmake . -G "Visual Studio 12"
  - cmake --build . --config RelWithDebInfo

notifications:
  - provider: Email
    to:
      - groonga-commit@lists.sourceforge.jp
      - kou@clear-code.com
    on_build_status_changed: true

before_test:
  - gem install grntest
test_script:
  - grntest --groonga src\groonga.exe --base-directory test\command
