version: "{build}"
clone_depth: 1
build_script:
  - cmake . -G "Visual Studio 12"
  - cmake --build . --config RelWithDebInfo

notifications:
  email:
    - groonga-commit@lists.sourceforge.jp

before_test:
  - gem install grntest
test_script:
  - grntest --groonga src\groonga.exe --base-directory test\command
