--- !ditz.rubyforge.org,2008-03-06/project 
name: groonga
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: groonga
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 1.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-10-06 07:24:04.165174 Z
    - daijiro <daijiro.mori@gmail.com>
    - created
    - the first major release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 1.1.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-10-06 07:25:48.624065 Z
    - daijiro <daijiro.mori@gmail.com>
    - created
    - ""
