--- !ditz.rubyforge.org,2008-03-06/project 
name: groonga
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: groonga
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-08-28 22:16:55.231603 Z
    - daijiro <daijiro.mori@gmail.com>
    - created
    - ""
